/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PenjualanApp;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormPenjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPenjualan
     */
    public FormPenjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderNameTxt = new javax.swing.JTextField();
        priceLandTxt = new javax.swing.JTextField();
        areaCombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buildingPriceTxt = new javax.swing.JTextField();
        prosesButton = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        radio30Button = new javax.swing.JRadioButton();
        radio50Button = new javax.swing.JRadioButton();
        radio70Button = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        largeLandTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        availableLandTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JTextField();
        dpTxt = new javax.swing.JTextField();
        installmentAmountTxt = new javax.swing.JTextField();
        ppnTxt = new javax.swing.JTextField();
        installmentMonthTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        agreementCbx = new javax.swing.JCheckBox();
        backButton = new javax.swing.JButton();

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah");

        jLabel3.setText("Area");

        priceLandTxt.setEditable(false);
        priceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        areaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "BOUGENVILE", "MELATI", "FLAMBOYAN" }));
        areaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboboxActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PenjualanApp/rumahM.jpeg"))); // NOI18N

        jLabel4.setText("Harga Bangunan");

        buildingPriceTxt.setEditable(false);
        buildingPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        prosesButton.setText("PROSES");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        deleteButton.setText("CLEAR");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("PPN (10%)");

        jLabel7.setText("Lama Angsuran");

        jLabel8.setText("DP");

        jLabel9.setText("Harga");

        jLabel10.setText("Type Rumah");

        RadioButton.add(radio30Button);
        radio30Button.setText("Type - 36");
        radio30Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio30ButtonActionPerformed(evt);
            }
        });

        RadioButton.add(radio50Button);
        radio50Button.setText("Type - 45");
        radio50Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio50ButtonActionPerformed(evt);
            }
        });

        RadioButton.add(radio70Button);
        radio70Button.setText("Type - 50");
        radio70Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio70ButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Luas Tanah ");

        largeLandTxt.setEditable(false);
        largeLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setText("Luas Tersedia");

        availableLandTxt.setEditable(false);
        availableLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setText("Cicilan");

        totalPriceTxt.setEditable(false);
        totalPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        dpTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        installmentAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ppnTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        installmentMonthTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Bulan");

        agreementCbx.setText("Setuju");
        agreementCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreementCbxActionPerformed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(orderNameTxt)
                                .addComponent(priceLandTxt)
                                .addComponent(areaCombobox, 0, 150, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backButton)))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prosesButton, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(radio30Button)
                    .addComponent(radio50Button)
                    .addComponent(radio70Button)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(installmentMonthTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ppnTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(installmentAmountTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPriceTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(availableLandTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(largeLandTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buildingPriceTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpan)
                        .addGap(30, 30, 30)
                        .addComponent(deleteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(agreementCbx))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(buildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(priceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio30Button)
                        .addComponent(largeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radio50Button)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio70Button)
                            .addComponent(availableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(installmentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(installmentMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(agreementCbx)))
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesButton)
                    .addComponent(simpan)
                    .addComponent(deleteButton)
                    .addComponent(backButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio30ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio30ButtonActionPerformed
        if (areaCombobox.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu");
            RadioButton.clearSelection();
        } else {
            largeLandTxt.setText("90");
            availableLandTxt.setText("60");
        long landPrice = Long.parseLong(priceLandTxt.getText()),
                buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                availableLand = Long.parseLong(availableLandTxt.getText()),
                totalPrice;
        totalPrice = (availableLand * landPrice)+  buildingPrice;
        totalPriceTxt.setText("" + totalPrice);
        
        installmentAmountTxt.setText("");
        dpTxt.setText("");
        ppnTxt.setText("");
        installmentMonthTxt.setText("");
        
        
        }
    }//GEN-LAST:event_radio30ButtonActionPerformed

    private void areaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboboxActionPerformed
        switch (areaCombobox.getSelectedIndex()){
            case 0:
                priceLandTxt.setText("");
                buildingPriceTxt.setText("");
                RadioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                dpTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                break;
            case 1:
                priceLandTxt.setText("500000");
                buildingPriceTxt.setText("90000000");
                RadioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                dpTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 2:
                priceLandTxt.setText("600000");
                buildingPriceTxt.setText("120000000");
                RadioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                dpTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            default:
                priceLandTxt.setText("700000");
                buildingPriceTxt.setText("150000000");
                RadioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                dpTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
        }
    }//GEN-LAST:event_areaComboboxActionPerformed

    private void radio50ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio50ButtonActionPerformed
         if (areaCombobox.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu");
            RadioButton.clearSelection();
        } else {
            largeLandTxt.setText("120");
            availableLandTxt.setText("100");
        long landPrice = Long.parseLong(priceLandTxt.getText()),
                buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                availableLand = Long.parseLong(availableLandTxt.getText()),
                totalPrice;
        totalPrice = (availableLand * landPrice)+  buildingPrice;
        totalPriceTxt.setText("" + totalPrice);
        
        installmentAmountTxt.setText("");
        dpTxt.setText("");
        ppnTxt.setText("");
        installmentMonthTxt.setText("");
        
        }
    }//GEN-LAST:event_radio50ButtonActionPerformed

    private void radio70ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio70ButtonActionPerformed
 if (areaCombobox.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu");
            RadioButton.clearSelection();
        } else {
            largeLandTxt.setText("140");
            availableLandTxt.setText("110");
        long landPrice = Long.parseLong(priceLandTxt.getText()),
                buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                availableLand = Long.parseLong(availableLandTxt.getText()),
                totalPrice;
        totalPrice = (availableLand * landPrice)+  buildingPrice;
        totalPriceTxt.setText("" + totalPrice);
        
        installmentAmountTxt.setText(""); 
        dpTxt.setText("");
        ppnTxt.setText("");
        installmentMonthTxt.setText("");
        }
    }//GEN-LAST:event_radio70ButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        orderNameTxt.setText("");
        priceLandTxt.setText("");
        buildingPriceTxt.setText("");
        largeLandTxt.setText("");
        availableLandTxt.setText("");
        totalPriceTxt.setText("");
        dpTxt.setText("");
        installmentAmountTxt.setText("");
        installmentMonthTxt.setText("");
        ppnTxt.setText("");
        areaCombobox.setSelectedIndex(0);
        RadioButton.clearSelection();
        agreementCbx.setSelected(false); 
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        if (totalPriceTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "ISI DATA DENGAN LEGKAP");
        } else if (dpTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "ISI KOLOM DP NYA");
        } else if (installmentAmountTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "ISI KOLOM LAMA ANGSURAN ");
        } else {
            long landPrice = Long.parseLong(priceLandTxt.getText()),
                buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                availableLand = Long.parseLong(availableLandTxt.getText()),
                dp = Long.parseLong(dpTxt.getText()),
                installmentAmount = Long.parseLong(installmentAmountTxt.getText()),
                totalPrice, ppn, installmentperMonth;
            totalPrice = (availableLand * landPrice)+buildingPrice;
            ppn= totalPrice * 10/ 100;
            installmentperMonth = (totalPrice + ppn)/ installmentAmount;
            ppnTxt.setText("" + ppn);
            installmentMonthTxt.setText(" " + installmentperMonth);
                    
        }
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void agreementCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreementCbxActionPerformed
        if(orderNameTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "ISI KOLOM NAMA TERLEBIH DAHULU");
        agreementCbx.setSelected(false);
        } else if (ppnTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "tekan tombol proses terlrbih dahulu");
        agreementCbx.setSelected(false);
        } else if (agreementCbx.isSelected()== true){
        JOptionPane.showMessageDialog(null, "ANDA MENYETUJUINYA");
        agreementCbx.setSelected(true);
        } else { 
            JOptionPane.showMessageDialog(null, "ANDA BELUM MENYETUJUI PESANAN");
            agreementCbx.setSelected(false);
        }
                
    }//GEN-LAST:event_agreementCbxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        OptionMenu optionMenu = new OptionMenu();
        optionMenu.setVisible(true);
        this.getDesktopPane().add(optionMenu);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
     try {
        String sql = "INSERT INTO tb_penjualan (nama_pesanan, area, tipe_rumah, luas_tanah, harga, lama_cicilan, cicilan_per_bulan) VALUES (?, ?, ?, ?, ?, ?, ?)";
        java.sql.Connection conn = koneksi.getConnection();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, orderNameTxt.getText());
        pst.setString(2, areaCombobox.getSelectedItem().toString());

        String tipe = "";
        if (radio30Button.isSelected()) tipe = "36";
        else if (radio50Button.isSelected()) tipe = "45";
        else if (radio70Button.isSelected()) tipe = "50";
        pst.setString(3, tipe);

        pst.setInt(4, Integer.parseInt(largeLandTxt.getText()));
        pst.setDouble(5, Double.parseDouble(totalPriceTxt.getText()));
        pst.setInt(6, Integer.parseInt(installmentAmountTxt.getText()));
        pst.setDouble(7, Double.parseDouble(installmentMonthTxt.getText()));

        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan: " + e.getMessage());
    }
    }//GEN-LAST:event_simpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RadioButton;
    private javax.swing.JCheckBox agreementCbx;
    private javax.swing.JComboBox<String> areaCombobox;
    private javax.swing.JTextField availableLandTxt;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField buildingPriceTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dpTxt;
    private javax.swing.JTextField installmentAmountTxt;
    private javax.swing.JTextField installmentMonthTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField largeLandTxt;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField ppnTxt;
    private javax.swing.JTextField priceLandTxt;
    private javax.swing.JButton prosesButton;
    private javax.swing.JRadioButton radio30Button;
    private javax.swing.JRadioButton radio50Button;
    private javax.swing.JRadioButton radio70Button;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField totalPriceTxt;
    // End of variables declaration//GEN-END:variables
}
